# Generated by Django 5.0.6 on 2024-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='domain',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_name',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
    ]
