# Generated by Django 5.0.6 on 2024-07-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uploadedfile_reviewer_uploadedfile_reviewer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_to_home2',
            field=models.BooleanField(default=None),
        ),
    ]
