# Generated by Django 5.0.6 on 2024-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_uploadedfile_uploaded_to_home2'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
